### ISSUE TITLE
Nested \tfrac repeatedly increases font-size.

### ISSUE THREAD

**Issue by mbostock** [Khan/KaTeX#1352]
In v0.10.0-alpha, it appears that nested \tfrac causes the font-size to balloon. For example:

```tex
\tfrac{1}{1+\tfrac{1}{1+\tfrac{1}{1+\tfrac{1}{1+\tfrac{1}{1+\tfrac{1}{1+\tfrac{1}{1+\tfrac{1}{2}}}}}}}}
```

![image](https://user-images.githubusercontent.com/230541/40497244-99e0fa2a-5f30-11e8-9be3-234c8d7a18f5.png)

Switching to \dfrac or \frac works around the issue:

![image](https://user-images.githubusercontent.com/230541/40497337-ca10e1b0-5f30-11e8-936a-a6a9e65a9be8.png)

![image](https://user-images.githubusercontent.com/230541/40497311-c0467dfc-5f30-11e8-94ba-6af2c34264bb.png)

Looking at the applied style, I think the issue is that it’s using em’s for font-size, which means that it’s relative to the containing font-size, and thus applies multiplicatively when nested rather than truly resetting the font-size.

```css
.katex .fontsize-ensurer.reset-size3.size6,
.katex .sizing.reset-size3.size6 {
    font-size: 1.42857143em;
}
```

Perhaps [rems](https://developer.mozilla.org/en-US/docs/Web/CSS/length#rem) would be appropriate here, rather than ems?
