### ISSUE TITLE
Simplify layout using flex box

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1409]
Flex box would allow us to simplify the markup we produce as well as allowing us to support commands that rely on the stretchiness/shrinkiness of glue.  Here's a prototype that use flex box for layout:

**Rendering:**
<img width="291" alt="screen shot 2018-06-05 at 1 09 10 am" src="https://user-images.githubusercontent.com/1044413/40956227-1799798a-685d-11e8-81ba-09e7c0aee82a.png">

**HTML**
```html
<span>
  1 +
  <span class="vbox" style="vertical-align:15px;">
    <span class="hbox">
      <span class="glue"></span>
      <span>1</span>
      <span class="glue"></span>
    </span>
    <span class="rule"></span>
    <span class="hbox">
      <span class="glue"></span>
      <span>
        1 + 
        <span class="vbox" style="vertical-align:14px;">
          <span class="hbox">
            <span class="glue"></span>
            1
            <span class="glue"></span>
          </span>
          <span class="rule"></span>
          <span class="hbox">
            <span class="glue"></span>
            x + 1
            <span class="glue"></span>
          </span>
        </span>  
      </span>
      <span class="glue"></span>
    </span>
  </span>
</span>
```

**CSS**
```css
body {
  font-size: 48px;
}

.vbox {
  display: inline-flex;
  flex-direction: column;
}

.hbox {
  display: inline-flex;
  flex-direction: row;
  width: 100%;
}

.rule {
  height: 4px;
  background: black;
}

.glue {
  flex-grow: 1;
  flex-shrink: 1;
}
```

https://jsfiddle.net/evhxcym0/14/
