### ISSUE TITLE
Browser "Reader View" shows both MathML and HTML

### ISSUE THREAD

**Issue by Apanatshka** [Khan/KaTeX#559]
The Reader View in Firefox works quite well in remove everything except de article in my browser. But because KaTeX uses hidden MathML, and Reader View ignores the CSS of that, I end up with duplicate formulas everywhere. Sadly they don't look at `aria-hidden`, though I'm also not sure if aria is meant for this kind of thing anyway. 

A quick search got me to this [bugzilla report](https://bugzilla.mozilla.org/show_bug.cgi?id=1144822) where reader view was extended to hide certain common CSS classes that are used for hidden elements in big frameworks. I found it in the `aboutReader.css`:

```css
/* Hide elements with common "hidden" class names */
.visually-hidden,
.visuallyhidden,
.hidden,
.invisible,
.sr-only {
  display: none;
}
```

Can one of these class names be added to the `katex-mathml` spans?
(Note that I'm not sure what will happen to screen reader functionality if the added CSS class is defined as `display: none` in the normal CSS of the website, which may use one of the common frameworks... I don't have a solution for that, other than maybe a customisation flag?)
