### ISSUE TITLE
\frac and subscript doesn't show properly

### ISSUE THREAD

**Issue by Rokt33r** [Khan/KaTeX#660]
![screen shot 2017-02-22 at 4 21 07](https://cloud.githubusercontent.com/assets/5865853/23180917/635e6ec4-f8b6-11e6-8965-e2452917374b.png)

I only applied https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/github-markdown.css and `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">`

Is there something I missed?

**Comment by Rokt33r** [comment]
This is my temporary solution. You can also check the result of this fix via the following link.

```css
/* Temporary fix for \frac and subscript */
.katex .frac-line {
  top: 0.85em;
  position: relative;
}
.katex .reset-textstyle.scriptstyle {
  top: 0.4em;
  position: relative;
}
```
> https://gist.github.com/Rokt33r/46f20b604ae3884276183b323c41e4d2
